### ISSUE TITLE
NaughtyAttributes.Buttons ans ScriptableObject serialization

### ISSUE THREAD

**Issue by Romaleks360** [dbrizov/NaughtyAttributes#118]
First of all, thank you for this brilliant extension! I'm including it in every project now. 

Recently I faced a problem that took much time to solve. I'm using [Button] on a few custom methods of my ScriptableObject, all of them modify serialized fields - for example, one function searches for other SO down in project hierarchy and adds them to an array.
After restarting Unity these changes are gone. Maybe it's obvious for those who are familiar with editor scripting, but at least this should be mentioned in the docs - you have to call EditorUtility.SetDirty(this); and AssetDatabase.SaveAssets(); in order to actually save changes caused by [Button]. Also, this functionality may be included in the extension itself with some other attribute or an optional parameter of Button.

**Comment by dbrizov** [comment]
Hi mate,

Thank you very much for the feedback.
I am not sure if it's a good idea to call **Editor** functions inside non-editor functions.
Maybe you need to add some preprocessor directives like **#if UNITY_EDITOR**, because the editor code will simply not compile when you create a build.
It's a good catch, however. I will mention it in the docs.

I can also call **SetDirty** inside the button property drawer if there are any serialization changes.

**Comment by dbrizov** [comment]
Fixed in 5e2c62ced066686f20cfe5455e1c41a859bcb7fd
