### ISSUE TITLE
[Request] Please Remove Buttons Section Label, Line, and Spacer

### ISSUE THREAD

**Issue by cjacobwade** [dbrizov/NaughtyAttributes#131]
Not a fan of the new buttons section. Adds a lot of uneeded visual noise and whitespace allowing less useful component info onscreen.

**Comment by dbrizov** [comment]
Hey mate.
I was actually thinking about that myself. It's not really needed for the buttons. I'll probably remove it.

The non-serialized fields and properties have the same separator. I am not sure if I should leave them like that, or remove it from them too. What do you think?

**Comment by cjacobwade** [comment]
I think those should also not have the labels. My reasoning being that the thing I appreciate most about NA is that it's very lightweight and unobtrustive, leaving all the control and responsibility for customization on the user.

**Comment by dbrizov** [comment]
Cool. Thanks for the feedback. I'll remove it

**Comment by dbrizov** [comment]
Fixed in **v2** - 4707a3770b13bfde62082968877d970e185eb2e0

The labels are not drawn by default.
The **DrawNonSerializedFields/Properties/Buttons** functions now have an optional parameter **drawHeader** that is **false** by default. If anyone wants the headers back, just change it to **true**.
I might add something like a **NaughtyAttributesSettings** scriptable object in the future for easy configuration
