### ISSUE TITLE
[Issue] UPM: Project has invalid dependencies

### ISSUE THREAD

**Issue by zxubian** [dbrizov/NaughtyAttributes#172]
I've been using the UPM package for a while, but when I tried to open the project on a new machine I got the following message:

![bug_not-a-tree](https://user-images.githubusercontent.com/8446683/91129460-0ab8bd80-e6e5-11ea-897f-cb53ef3342f0.png)

This is what my manifest.json looks like:
```

{
  "dependencies": {
    "com.dbrizov.naughtyattributes": "https://github.com/dbrizov/NaughtyAttributes.git#upm",
   .....................................................................................................
    "com.unity.modules.xr": "1.0.0"
  },
  "lock": {
    "com.dbrizov.naughtyattributes": {
      "revision": "upm",
      "hash": "8361c4c50a4f375cfac3cdb67ebd3babf15c42d8"
    }
  }
}

```

The problem goes away when I delete the "lock" segment in the manifest.json file. Then the package gets reimported, the lock segment reappears, but gets a different hash value.

None of the other custom git-based UPM packages that I've used produce these locks.

System info:
* Unity Version: 2019.4.0f1
* Windows 10 x64

**Comment by dbrizov** [comment]
Hmm, I've never encountered that issue. I don't know why this is happening. I recently made an update from **v2.0.4** to **v2.0.5**. Maybe the hash changes that way and a reimported is needed?

**Comment by dbrizov** [comment]
Are you sure other upm git packages don't produce a lock? I think all git packages produce a lock.

**Comment by zxubian** [comment]
@dbrizov 
I've used the following packages and neither of them produce locks. They all are registered in the same way as yours, either by adding a line to manifest.json or by adding a git reference via the UPM UI.

https://github.com/Cysharp/UniTask
https://github.com/Siccity/GLTFUtility

**Comment by dbrizov** [comment]
It seems the lock is intended: [Git Packages Lock](https://forum.unity.com/threads/preventing-the-manifest-json-from-locking-custom-git-packages.822555/)
I guess, because the hash changed, the lock was broken and it forces a manual update. I also think it has something to do with the fact that Unity now created a separate .json file for locks only. It's called `packages-lock.json` and is located next to the `manifest.json`

If you want to prevent locking, you can install NaughtyAttributes via [openupm](https://openupm.com/packages/com.dbrizov.naughtyattributes/). This way there will be a scoped registry inside of a lock inside the `manifest.json` and it won't force an update next time I update the package.
