### ISSUE TITLE
Adding package to manifest.json fails when it's updated

### ISSUE THREAD

**Issue by Oletus** [dbrizov/NaughtyAttributes#190]
We've been using the package by adding this line to manifest.json as instructed in the README:

`"com.dbrizov.naughtyattributes": "https://github.com/dbrizov/NaughtyAttributes.git#upm"`

However, if the package has been updated and the Unity project is opened on a new machine that doesn't have the package cached in Library, this option fails at least in Unity 2019.4 and 2020.1. Maybe this is because Unity stores the commit hash to packages-lock.json when it initially downloads the package, and old commits have been removed from history when the upm branch has been updated, so Unity can't download the matching commit anymore.

**Comment by dbrizov** [comment]
I've already fixed the history, and the upm is updated, and not deleted every time I push to master: #188 
The lock in the **package-locks.json** doesn't update however, so you will be using the version from the old commit. You need to update the hash manually, or you can reimport it using the Unity Editor.
I've recreated the upm branch one last time yesterday, so the old history is lost, maybe that's why you are experiencing some issues. From now on, however, everything should be fine.
