### ISSUE TITLE
Inquiry of Contribution

### ISSUE THREAD

**Issue by DarkMio** [dbrizov/NaughtyAttributes#202]
Hi - we've picked up your tool for us in production on our product and after studying the source code for a bit, we'd like to make incremental updates to your library if you're interested in that.

This list might change, but generally I'm currently working on some refinements, from which I'm gathering some thoughts first, before going into pull-requests.

## MetaAttributes

Currently we're reworking a bit of that, by pulling all sorted MetaAttributes out of a property and filtering by types - allowing us to query the type once with reflection, giving minor benefits in speed.

Additionally there are a few interfaces to do just that, making contracting between types and attributes easier by just reducing the type to the essentials.

## EnableIfBase

We've refactored that out, so that the base merely implements a public getter if the attribute enables it:

```
public abstract class AbstractEnabledAttribute : MetaAttribute, IEnabledAttribute
{
  public abstract bool Enabled { get; }
}
```

This way we're shifting the conditional operators and all special operational logic to the implementing classes, allowing us to make quicker additions, from which we have a few:

- EnabledInPlaymode
- DisabledInPlaymode
- EnabledInEditmode
- DisabledInEditmode
- VisibleInEditmode
- HiddenInEditmode
- VisibleInPlaymode
- HiddenInPlaymode

## IMGUI + UI Toolkit

We're currently wobbling ourselves around the problem and have not a good answer to that yet.

## Language

We're continuing to develop this with the language features available in 2018.4 (the package currently mentions 2018.3)

## API

We're committed to keep the user-facing API the same. 

## Packaging

I have a lot of experience in packaging Unity Packages properly, I'm currently investing some time to refactor the folder layout and location of the package-fied project to match the expectations of the package manager. That includes how sample-files are loaded (that one is the most tricky), location of the package as well as certain meta-files and such.

We do internally via azure-devops a publish of your package and could share some insights of workflows, since the underlying software of github-actions and azure-pipelines is (almost) the same.

---

If you have any thoughts to share and how you would like us to proceed in updating, I'm happy to help and contribute back. I just didn't want to charge forward with more-or-less invasive PRs before we could coordinate that a bit.

**Comment by dbrizov** [comment]
Hi, and sorry for the late reply.

### About the PRs
Thanks for taking an interest in contributing.
I'd like to see what you've done. It will be very nice if you could make different pull requests for the different features:
- PR for the rework of MetaAttributes
- PR for the new `Enabled` attributes. I think they are a great addition

### About the IMGUI + UI toolkit
Are you referring to the new UI Elements system? Some people mentioned that NaughtyAttributes is not working with custom property drawers implemented with the new system. I still haven't done anything about that. It's on my TODO list, I just wanted the new system to get out of beta. I am not sure if it already is, I have to check that.

### About the packaging
What exactly are your proposals? I followed Unity's guidelines for the packages folder structure, and I don't think there are any problems. As for distribution, I had some issues with the github-actions, because I was recreating the UPM branch every time I updated the package, and all users had to reimport it, because the hash of the last commit of the previous version was different, and Unity doesn't like that. That is history, fortunately. You can also install it via [openupm](https://openupm.com/), or the [asset store](https://assetstore.unity.com/packages/tools/utilities/naughtyattributes-129996). Some people were proposing to make a Nuget distribution #117, but I still haven't done that. I really want to automate the whole process somehow, but I don't have much free time these days. I am trying to update the package ones every 1-2 months

**Comment by DarkMio** [comment]
About PRs: Noted, I'll gather our internal changes and make small, incremental updates.  For a general timeline, I'm probably taking my time today or tomorrow to start with PRs. I've refactored some of the Inspector code, giving an option for this:

```cs
// ...
[Button, DisabledInEditMode]
private void FooMethod() { }
```

rather than

```cs
// ...
[Button(enabled: EPlaymode)]
private void FooMethod() { }
```

This works, in theory, with other cases (like native properties and non-serialized fields) too, giving (probably, I haven't tested that) the option to edit runtime properties from the inspector.

On IMGUI + UI Toolkit: We had little experience with that yet, haven't faced issues but would be probably investigate as soon as we face the issue.

On Packaging: Currently your folder structure places NaughtyAssets inside the Assets folder, rather than the Packages Folder. (On top of my head) that was an issue with Unity 2018.4 to edit a package when it resided in that folder, but that has been resolved for a while. To dive a bit into the process:

![](https://i.miomoto.de/h92Jiu.png)

We have internally moved the NaughtyAttributes folder into Packages as package-development and renamed `Documentation` to `Documentation~` - additionally added the package-development dependencies from Unity (seen in the screenshot). This enabled the "publish" button. We then have a build-script, that does the "Publish to Disk..." operation from command-line, which (among other things) renames the `Samples` folder into `Samples~`. We then use npm directly to push the resulting tarball against our internal registry.

I can confirm that the move from `Assets/` to `Packages/` works well with VSCode, Visual Studio and Rider in Unity 2019.4+, since the removal of false write-protections from prior editor versions,
