### ISSUE TITLE
Custom property field doesn't take into account ReorderableListAttribute

### ISSUE THREAD

**Issue by pawelsalwa** [dbrizov/NaughtyAttributes#239]
Hello,
There's custom inspector with EditorGuiLayout.PropertyField(property); This property is simple serialized List<int>. The inspector though shows default Unitys List<int> view. It doesn't take into account ReorderableListAttribute. Is it a bug or I don't understand how serializedProperties with property attribute are drawn? Maybe EditorGuiLayout.PropertyField omits PropertyAttribute?

**Comment by dbrizov** [comment]
If you are implementing you custom property drawer, and you want ReorderableList to work, you need use NaughtyAttribute's version of `EditorGUILayout.PropertyField` functions.

Check this from the documentation:
![Screenshot from 2021-06-26 10-03-21](https://user-images.githubusercontent.com/3619573/123505147-0becab00-d666-11eb-97b7-4ec1358b8e4a.png)

You might also want to update to Unity `2020.2.x+`, because lists are reorderable by default
