### ISSUE TITLE
ShowIf, HideIf, and DisableIf do not work with properties

### ISSUE THREAD

**Issue by JimmyCushnie** [dbrizov/NaughtyAttributes#63]
These attributes work with bool fields and methods that return a bool, but they do not work with get-enabled bool properties. Adding support shouldn't be too hard because you can use reflection to get the property's `GetMethod` and use that.

**Comment by xahon** [comment]
I can't make them work even with fields

**Comment by JimmyCushnie** [comment]
I notice you're closing a lot of issues without explanation. When you close an issue, can you leave a comment saying "this is fixed in commit x" or "I've decided not to fix this for x reason"?

**Comment by dbrizov** [comment]
I actually closed this one by mistake. I am closing the ones that I will not fix in this version of the project. I am reworking everything from scratch (in a **v2** branch) because most of the issues are very hard to fix because of the architecture of the project. A lot of people want nesting support. I was struggling to do it with recursion in the past couple of days, but it's pretty hard. I am just reviewing the issues so that I can address them on the go while I am doing the **v2**.

**Comment by JimmyCushnie** [comment]
That makes sense. But if you're using this repo for v2, I think it makes sense to keep issues open until they're fixed in v2.

**Comment by dbrizov** [comment]
Fixed in version 2.0.0
