### ISSUE TITLE
Nesting incapability limits usefulness of this project a lot

### ISSUE THREAD

**Issue by Samhayne** [dbrizov/NaughtyAttributes#91]
This is more a warning to other devs than a bug report.

NaughtyAttributes would just draw a default inspector if you do nesting like this:

```
[Serializable]
public class Inner
{
	public bool Check;

	[NaughtyAttributes.ShowIf("Check")]
	public string hello = "hello";
}


public class NestingTest : MonoBehaviour
{
	public Inner innerTest;
}

```

Same goes for structs.

If you need this, go look somewhere else.
If you don't: wonderful project.

Also see: https://github.com/dbrizov/NaughtyAttributes/issues/19

**Comment by dbrizov** [comment]
I know. The whole architecture is not written correctly, and it's
impossible to make nesting at the moment. I am thinking of rewriting the
whole thing. Unfortunately, I am pretty busy and don't have time. I haven't
updated the project recently due to the lack of free time.

**Comment by JanRichardsonDR** [comment]
I found that its pretty simple to rework the code, into a generic property drawer, which you then can then inherit from to implement a property drawer for each serializable type. 

The main part of the work is to adapt the code to work with objects instead of UnityEngine.Objects for the reflection lookups and modify GetTargetObject to work from the path rather than the name and iterating the objects to get to the correspond element.

**Comment by worstgamedev** [comment]
any update?

**Comment by dbrizov** [comment]
Read my last comment here #103

**Comment by dbrizov** [comment]
Nesting is now supported. However, there are some exceptions. Only serialized properties support nesting. **BoxGroup**, **Button**, **ShowNativePropert**y, **ShowNonSerializedField** and **ReorderableList** don't support nesting. This is because they are not implemented with Unity's **CustomPropertyDrawer**. I tried a custom solution with recursion. I had major issues and it wasn't working very well. There is also an issue with the **Dropdown** attribute. When nested inside a struct the value doesn't update. The reason for that is that in order to update the value of the struct via reflection I need to *box/unbox* the struct. It is already boxed because I am working with objects in the low-level API, but I don't know the compile-time type of the struct to unbox it. For now you can nest it in classes only. I am working on a more detailed documentation so all of these will be mentioned.

**Comment by Samhayne** [comment]
Hi, @dbrizov !
I was about to upgrade our prpject with your new version... but nesting didn't work for me.
To make sure I tried out my example above... it didn't work. Should it?

**Comment by dbrizov** [comment]
Yes mate, it should work. You have to put an attribute, however. Like this

```
[Serializable]
public class Inner
{
	public bool Check;

	[NaughtyAttributes.ShowIf("Check")]
        [AllowNesting]
	public string hello = "hello";
}


public class NestingTest : MonoBehaviour
{
	public Inner innerTest;
}
```

You can read more about the **AllowNesting** attribute [here](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html)

**Comment by Samhayne** [comment]
Thanks for your quick reply! @dbrizov.

Ahhh. I missed that! Yes!! It works. 👍 
So cool you implemented that!

It's just a bit sad that the validator error boxes are drawn at the end of the inspector-
But I see your struggle to hack this in at all.


`[Serializable]
public class Inner
{
	public bool Check;

	[NaughtyAttributes.ValidateInput("Validate", "Hello!"), AllowNesting]
	public string hello = "Hello!";

	[NaughtyAttributes.ValidateInput("Validate", "Hooray!"), AllowNesting]
	public string hooray = "Hooray";

	public bool Validate(string helloString)
	{
		return Check;
	}
}


public class NestingTest : MonoBehaviour
{
	public Inner innerTest;
}`


![image](https://user-images.githubusercontent.com/7030482/96333596-2e580e80-106b-11eb-857e-830e753b0752.png)
